name: Build Python Executable

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Run on Linux, Windows, and macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use your preferred Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy kivymd flask flask-cors pyrebase

    - name: Install Nuitka
      run: python -m pip install nuitka

    - name: Build Executable
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          python -m nuitka --standalone --onefile --output-dir=dist main.py
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          python -m nuitka --standalone --onefile --windows-icon-from-ico=logo.ico --windows-company-name="Gofaone Tlalang" --windows-product-name="MemerDevs" --output-dir=dist main.py
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          python -m nuitka --standalone --onefile --output-dir=dist main.py
        fi

    - name: Archive Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: dist/  # Upload the `dist` directory as an artifact