name: 'Kivy App to Executables'

# Define the event that triggers the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build-executables:
    name: Build Python Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install imageio pillow urllib3 requests kivy kivymd pyrebase4 plyer setuptools 
          
      - name: Install Nuitka
        run: python -m pip install nuitka

      - name: Build Executable
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            python -m nuitka --standalone --static-libpython=yes --linux-icon=logo.ico --onefile --output-dir=dist main.py
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            python -m nuitka --standalone --macos-app-icon=logo.ico --static-libpython=yes --onefile --output-dir=dist main.py
          fi
        shell: bash

      - name: Clean up intermediate build files
        run: |
          rm -rf build __pycache__
        shell: bash

      - name: Compress Executables (Max Compression)
        run: |
          zip -9 -r executables-${{ matrix.os }}.zip dist/*
        shell: bash

      - name: Upload OS-specific Executables as artifact
        uses: actions/upload-artifact@v3
        with:
          name: executables-${{ matrix.os }}
          path: executables-${{ matrix.os }}.zip
