name: 'Kivy App to APK, IPA, and Executables'

# Define the event that triggers the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:       
  build-executables:
    name: Build Python Executables
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install imageio pillow urllib3 requests kivy kivymd pyrebase4 plyer setuptools

      - name: Install zip
        run: |
          choco install zip -y
        shell: bash

      - name: Install Pyinstaller
        run: python -m pip install pyinstaller

      - name: Build Executable
        run: |
          python -m PyInstaller --name MemerDevs --onefile --standalone --noconfirm --icon=logo.ico main.py
        shell: bash

      - name: Clean up intermediate build files
        run: |
          rm -rf build __pycache__
        shell: bash

      - name: Compress Executables (Max Compression)
        run: |
          zip -9 -r executables-windows-latest.zip dist/*
        shell: bash

      - name: Upload OS-specific Executables as artifact
        uses: actions/upload-artifact@v3
        with:
          name: executables-windows-latest
          path: executables-windows-latest.zip
