name: Build MemerDevs App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy kivymd plyer urllib3 requests pyrebase4 pyinstaller

      - name: Download Mesa3D
        run: |
          curl -L -o mesa3d.zip https://github.com/pal1000/mesa-dist-win/releases/download/23.1.1/mesa3d-23.1.1-release-msvc.zip
          if not exist mesa3d.zip (
            echo "Mesa3D download failed." && exit 1
          )

      - name: Extract Mesa3D
        run: |
          mkdir mesa3d
          powershell -Command "Expand-Archive -Path mesa3d.zip -DestinationPath mesa3d"

      - name: Configure Mesa3D for OpenGL
        run: |
          echo Configuring Mesa3D for software OpenGL rendering
          setx MESA_GL_VERSION_OVERRIDE 2.1
          setx PATH "%PATH%;%cd%/mesa3d"

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --name MemerDevs --onefile --noconfirm --icon=logo.ico main.py

      - name: Archive and compress the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: MemerDevs
          path: dist/MemerDevs.exe
          retention-days: 7
          if-no-files-found: error
