name: Build and Package MemerDevs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy kivymd plyer urllib3 requests pyrebase4 nuitka

      - name: Freeze dependencies
        run: |
          pip freeze > requirements.txt
          mkdir distribution
          move requirements.txt distribution/

      - name: Compile with Nuitka
        run: |
          python -m nuitka --follow-imports --output-dir=distribution main.py
        shell: cmd

      - name: Copy dependencies
        run: |
          mkdir distribution/dependencies
          pip download -d distribution/dependencies -r distribution/requirements.txt

      - name: Compress for Distribution
        run: |
          cd distribution
          powershell Compress-Archive -Path . -DestinationPath MemerDevs_Distribution.zip -CompressionLevel Optimal

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MemerDevs_Distribution
          path: distribution/MemerDevs_Distribution.zip
          retention-days: 7
